### ISSUE TITLE
Could not initialize a database connection: could not find driver

### ISSUE THREAD

**Issue by cflinspach** [NagVis/nagvis#119]
We're using PHP7 and nagvis 1.9.2, we've also tried 1.9b7 and saw #51, we're still getting this on the webpage:

```
Error: (0) Undefined property: CorePDOHandler::$dsn
URL: /nagvis/frontend/nagvis-js/index.php
File: /usr/local/nagvis/share/server/core/classes/CoreAuthModPDO.php
Line: 58
#0 /usr/local/nagvis/share/server/core/classes/CoreAuthModPDO.php(58): nagvisExceptionErrorHandler(8, 'Undefined prope...', '/usr/local/nagv...', 58, Array)
#1 /usr/local/nagvis/share/server/core/classes/CoreAuthHandler.php(47): CoreAuthModPDO->__construct()
#2 /usr/local/nagvis/share/server/core/functions/index.php(44): CoreAuthHandler->__construct()
#3 /usr/local/nagvis/share/frontend/nagvis-js/index.php(53): require('/usr/local/nagv...')
#4 {main}
```

We see in the apache log:
`Could not initialize a database connection: could not find driver
`

**Comment by LarsMichelsen** [comment]
Seems your installation misses some PHP / PDO dependencies. You need PDO/SQLite support in your php installation.

**Comment by cflinspach** [comment]
We've done some work trying different versions and are getting a different error on the webpage but the same error in the logs. This time we started by getting the [NagVis](https://packages.ubuntu.com/trusty/net/nagvis) package with apt-get to get the dependencies and then we moved up versions trying to get one that works. Here's where we are currently. 

Error on page:
```
Error: (0) filemtime(): stat failed for /etc/nagvis/conf.d (/usr/share/nagvis/share/server/core/classes/GlobalMainCfg.php:1270)

#0 [internal function]: nagvisExceptionErrorHandler(2, 'filemtime(): st...', '/usr/share/nagv...', 1270, Array)
#1 /usr/share/nagvis/share/server/core/classes/GlobalMainCfg.php(1270): filemtime('/etc/nagvis/con...')
#2 /usr/share/nagvis/share/server/core/functions/core.php(38): GlobalMainCfg->init()
#3 /usr/share/nagvis/share/frontend/nagvis-js/index.php(44): require('/usr/share/nagv...')
#4 {main}
```

Apache2 Error.log:
```
[Thu Jul 06 11:06:17.511468 2017] [:error] [pid 31234] [client 192.168.0.10:46694] Could not initialize a database connection: could not find driver
```

dpkg -l | grep '^ii' | grep php
```
ii  libapache2-mod-php7.0                      7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                                 1:52+deb.sury.org~xenial+1                               all          Common files for PHP packages
ii  php-dompdf                                 0.6.1+dfsg-2ubuntu1                                      all          HTML to PDF converter
ii  php-font-lib                               0.2.2+dfsg-2build1                                       all          read, parse, export and make subsets of different fonts
ii  php-gd                                     1:7.1+52+deb.sury.org~xenial+1                           all          GD module for PHP [default]
ii  php-gettext                                1.0.11-2+deb.sury.org~xenial+1                           all          read gettext MO files directly, without requiring anything other than PHP
ii  php-htmlpurifier                           4.7.0-1build1                                            all          Standards-compliant HTML filter
ii  php-icinga                                 2.4.1-1~ppa1604+1                                        all          PHP library to communicate with and use Icinga
ii  php-imagick                                3.4.3-1~ubuntu16.04.1+deb.sury.org+1                     amd64        Provides a wrapper to the ImageMagick library
ii  php-mysql                                  1:7.1+52+deb.sury.org~xenial+1                           all          MySQL module for PHP [default]
ii  php-net-socket                             1.0.14-1build1                                           all          PHP PEAR Network Socket Interface module
ii  php-pear                                   1:1.10.4+submodules+notgz-1~ubuntu16.04.1+deb.sury.org+1 all          PEAR Base System
ii  php-sqlite3                                1:7.1+52+deb.sury.org~xenial+1                           all          SQLite3 module for PHP [default]
ii  php7.0                                     7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.0-cli                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        command-line interpreter for the PHP scripting language
ii  php7.0-common                              7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        documentation, examples and common module for PHP
ii  php7.0-curl                                7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        CURL module for PHP
ii  php7.0-dba                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        DBA module for PHP
ii  php7.0-gd                                  7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        GD module for PHP
ii  php7.0-intl                                7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        Internationalisation module for PHP
ii  php7.0-json                                7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        JSON module for PHP
ii  php7.0-ldap                                7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        LDAP module for PHP
ii  php7.0-mbstring                            7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        MBSTRING module for PHP
ii  php7.0-mysql                               7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        MySQL module for PHP
ii  php7.0-opcache                             7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        Zend OpCache module for PHP
ii  php7.0-readline                            7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        readline module for PHP
ii  php7.0-xml                                 7.0.20-2~ubuntu16.04.1+deb.sury.org+1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.1-common                              7.1.6-1~ubuntu16.04.1+deb.sury.org+1                     amd64        documentation, examples and common module for PHP
ii  php7.1-gd                                  7.1.6-1~ubuntu16.04.1+deb.sury.org+1                     amd64        GD module for PHP
ii  php7.1-mysql                               7.1.6-1~ubuntu16.04.1+deb.sury.org+1                     amd64        MySQL module for PHP
ii  php7.1-sqlite3                             7.1.6-1~ubuntu16.04.1+deb.sury.org+1                     amd64        SQLite3 module for PHP
```

Info from the last install.sh we ran.
```
+------------------------------------------------------------------------------+
| Welcome to NagVis Installer 1.9.2                                            |
+------------------------------------------------------------------------------+
| This script is built to facilitate the NagVis installation and update        |
| procedure for you. The installer has been tested on the following systems:   |
| - Debian, since Etch (4.0)                                                   |
| - Ubuntu, since Hardy (8.04)                                                 |
| - SuSE Linux Enterprise Server 10 and 11                                     |
|                                                                              |
| Similar distributions to the ones mentioned above should work as well.       |
| That (hopefully) includes RedHat, Fedora, CentOS, OpenSuSE                   |
|                                                                              |
| If you experience any problems using these or other distributions, please    |
| report that to the NagVis team.                                              |
+------------------------------------------------------------------------------+
| Do you want to proceed? [y]: 
+------------------------------------------------------------------------------+
| Starting installation of NagVis 1.9.2                                        |
+------------------------------------------------------------------------------+
| OS  : Ubuntu 16.04.2 LTS                                                     |
|                                                                              |
+--- Checking for tools -------------------------------------------------------+
| Using packet manager /usr/bin/dpkg                                     found |
|                                                                              |
+--- Checking paths -----------------------------------------------------------+
| Please enter the path to the icinga2 base directory [/usr/local/icinga]: /etc/icinga2
|   icinga2 path /etc/icinga2                                            found |
| Please enter the path to NagVis base [/usr/local/icinga/nagvis]: /etc/nagvis
|                                                                              |
+--- Checking prerequisites ---------------------------------------------------+
| PHP 7.0                                                                found |
|   PHP Module: gd compiled_in                                           found |
|   PHP Module: mbstring compiled_in                                     found |
|   PHP Module: gettext compiled_in                                      found |
|   PHP Module: session compiled_in                                      found |
|   PHP Module: xml compiled_in                                          found |
|   PHP Module: pdo compiled_in                                          found |
|   Apache mod_php                                                       found |
| Do you want to update the backend configuration? [n]: n
| Graphviz 2.38                                                          found |
|   Graphviz Module dot 2.38.0                                           found |
|   Graphviz Module neato 2.38.0                                         found |
|   Graphviz Module twopi 2.38.0                                         found |
|   Graphviz Module circo 2.38.0                                         found |
|   Graphviz Module fdp 2.38.0                                           found |
| SQLite 3.11                                                            found |
|                                                                              |
+--- Trying to detect Apache settings -----------------------------------------+
| Please enter the web path to NagVis [/nagvis]: 
| Please enter the name of the web-server user [www-data]: 
| Please enter the name of the web-server group [www-data]: 
| create Apache config file [y]: 
|                                                                              |
+--- Checking for existing NagVis ---------------------------------------------+
| NagVis 1.8.5                                                           found |
| Do you want the installer to update your config files when possible? [y]: 
| Remove backup directory after successful installation? [n]: 
|                                                                              |
+------------------------------------------------------------------------------+
| Summary                                                                      |
+------------------------------------------------------------------------------+
| NagVis home will be:           /etc/nagvis                                   |
| Owner of NagVis files will be: www-data                                      |
| Group of NagVis files will be: www-data                                      |
| Path to Apache config dir is:  /etc/apache2/conf-available                   |
| Apache config will be created: yes                                           |
|                                                                              |
| Installation mode:             update                                        |
| Old version:                   1.8.5                                         |
| New version:                   1.9.2                                         |
| Backup directory:              /etc/nagvis.old-2017-07-06_10:50:24           |
|                                                                              |
| Note: The current NagVis directory will be moved to the backup directory.    |
|       The backup directory will be NOT removed after successful installation |
|       Your configuration files will be copied.                               |
|       The configuration files will be updated if possible.                   |
|                                                                              |
| Do you really want to continue? [y]: 
+------------------------------------------------------------------------------+
| Starting installation                                                        |
+------------------------------------------------------------------------------+
| Moving old NagVis to /etc/nagvis.old-2017-07-06_10:50:24..             done  |
| Creating directory /etc/nagvis...                                      done  |
| Creating directory /etc/nagvis/var...                                  done  |
| Creating directory /etc/nagvis/var/tmpl/cache...                       done  |
| Creating directory /etc/nagvis/var/tmpl/compile...                     done  |
| Creating directory /etc/nagvis/share/var...                            done  |
| Copying files to /etc/nagvis...                                        done  |
| Creating directory /etc/nagvis/etc/profiles...                         done  |
| Creating main configuration file...                                    done  |
| adding base="/etc/nagvis"                                              done  |
| adding htmlcgi=/icinga2/cgi-bin                                        done  |
| adding dbname=icinga2                                                  done  |
| adding dbprefix=icinga2_                                               done  |
|   Adding webserver group to file_group...                              done  |
| Creating web configuration file...                                     done  |
| Setting permissions for web configuration file...                      done  |
|                                                                              |
| Restoring main configuration file(s)...                                done  |
| Restoring custom map configuration files...                            done  |
| Restoring custom geomap source files...                                done  |
| Restoring user configuration files...                                  done  |
| Restoring conf.d/ configuration files...                               done  |
| Restoring custom map images...                                         done  |
| Restoring custom gadget images...                                      done  |
| Restoring custom iconsets...                                           done  |
| Restoring custom shapes...                                             done  |
| Restoring custom templates...                                          done  |
| Restoring custom template images...                                    done  |
| Restoring custom gadgets...                                            done  |
| Restoring custom scripts...                                            done  |
| Restoring auth database file...                                        done  |
| Restoring custom stylesheets...                                        done  |
|                                                                              |
+------------------------------------------------------------------------------+
| Handling changed/removed options                                             |
+------------------------------------------------------------------------------+
| Removing allowedforconfig option from main config...                   done  |
| Removing autoupdatefreq option from main config...                     done  |
| Removing htmlwuijs option from main config...                          done  |
| Removing wuijs option from main config...                              done  |
| Removing showautomaps option from main config...                       done  |
| Removing usegdlibs option from main config...                          done  |
| Removing displayheader option from main config...                      done  |
| Removing hovertimeout option from main config...                       done  |
| Removing requestmaxparams option from main config...                   done  |
| Removing requestmaxlength option from main config...                   done  |
| Removing allowed_for_config option from map configs...                 done  |
| Removing allowed_user from map configs...                              done  |
| Removing hover_timeout from map configs...                             done  |
| Removing usegdlibs from map configs...                                 done  |
| Removing gadget_type from map configs...                               done  |
+------------------------------------------------------------------------------+
| HINT: Please check the changelog or the documentation for changes which      |
|       affect your configuration files                                        |
|                                                                              |
+--- Setting permissions... ---------------------------------------------------+
| /etc/nagvis/etc/nagvis.ini.php-sample                                  done  |
| /etc/nagvis/etc                                                        done  |
| /etc/nagvis/etc/maps                                                   done  |
| /etc/nagvis/etc/maps/*                                                 done  |
| /etc/nagvis/etc/geomap                                                 done  |
| /etc/nagvis/etc/geomap/*                                               done  |
| /etc/nagvis/etc/profiles                                               done  |
| /etc/nagvis/share/userfiles/images/maps                                done  |
| /etc/nagvis/share/userfiles/images/maps/*                              done  |
| /etc/nagvis/share/userfiles/images/shapes                              done  |
| /etc/nagvis/share/userfiles/images/shapes/*                            done  |
| /etc/nagvis/var                                                        done  |
| /etc/nagvis/var/*                                                      done  |
| /etc/nagvis/var/tmpl                                                   done  |
| /etc/nagvis/var/tmpl/cache                                             done  |
| /etc/nagvis/var/tmpl/compile                                           done  |
| /etc/nagvis/share/var                                                  done  |
|                                                                              |
+------------------------------------------------------------------------------+
| Installation complete                                                        |
|                                                                              |
| You can safely remove this source directory.                                 |
|                                                                              |
| For later update/upgrade you may use this command to have a faster update:   |
| ./install.sh -n /etc/icinga2 -p /etc/nagvis -u www-data -g www-data -w /etc/apache2/conf-available -a y
|                                                                              |
| What to do next?                                                             |
| - Read the documentation                                                     |
| - Maybe you want to edit the main configuration file?                        |
|   Its location is: /etc/nagvis/etc/nagvis.ini.php                            |
| - Configure NagVis via browser                                               |
|   <http://localhost/nagvis/config.php>                                       |
| - Initial admin credentials:                                                 |
|     Username: admin                                                          |
|     Password: admin                                                          |
+------------------------------------------------------------------------------+
```

**Comment by cflinspach** [comment]
I got it. I uninstalled `php-sqlite3` and installed `php7.0-sqlite3` then enabled them by uncommenting `extension=php_pdo_mysql.dll` in my `php.ini`
