### ISSUE TITLE
Nagvis Undefined property: CorePDOHandler:

### ISSUE THREAD

**Issue by USER1696960** [NagVis/nagvis#177]
Hi everyone,

Im fighting with Nagvis since 2 months, and I can't figured out the error I have. Nagios works just fine, but not NagVis. When I want to make a new map and add a host, it throws this error:

`Failed to get objects: Error: (0) Undefined property: CorePDOHandler::$data<div class="details">URL: /nagvis/server/core/ajax_handler.php?mod=Map&act=addModify&show=2&type=host&x=438&y=224&_ajaxid=1545223538<br> File: /usr/local/nagvis/share/server/core/classes/CorePDOHandler.php<br> Line: 306<br> <code>#0 /usr/local/nagvis/share/server/core/classes/CorePDOHandler.php(306): nagvisExceptionErrorHandler(8, 'Undefined prope...', '/usr/local/nagv...', 306, Array)<br> 
#1 /usr/local/nagvis/share/server/core/classes/CorePDOHandler.php(332): CorePDOHandler->prep('SELECT name1,na...')<br> 
#2 /usr/local/nagvis/share/server/core/classes/GlobalBackendPDO.php(250): CorePDOHandler->query('SELECT name1,na...', Array)<br> 
#3 /usr/local/nagvis/share/server/core/mapcfg/default.php(145): GlobalBackendPDO->getObjects('host', '', '')<br> 
#4 /usr/local/nagvis/share/server/core/mapcfg/default.php(159): getObjectNames('host', Object(GlobalMapCfg), NULL, Array)<br> 
#5 /usr/local/nagvis/share/server/core/classes/ViewMapAddModify.php(394): listHostNames(Object(GlobalMapCfg), NULL, Array)<br> 
#6 /usr/local/nagvis/share/server/core/classes/ViewMapAddModify.php(509): ViewMapAddModify->drawField('host_name', Array, Array)<br> 
#7 /usr/local/nagvis/share/server/core/classes/ViewMapAddModify.php(537): ViewMapAddModify->drawFields(Array)<br> 
#8 /usr/local/nagvis/share/server/core/classes/ViewMapAddModify.php(620): ViewMapAddModify->drawForm()<br> 
#9 /usr/local/nagvis/share/server/core/classes/CoreModMap.php(133): ViewMapAddModify->parse()<br> 
#10 /usr/local/nagvis/share/server/core/functions/index.php(120): CoreModMap->handleAction()<br> 
#11 /usr/local/nagvis/share/server/core/ajax_handler.php(59): require('/usr/local/nagv...')<br> 
#12 {main}</code>Output: <pre>&lt;form id=&quot;addmodify&quot; name=&quot;addmodify&quot; action=&quot;javascript:submitForm('/nagvis/server/core/ajax_handler.php?mod=Map&amp;amp;act=addModify', 'addmodify');&quot; method=&quot;POST&quot;&gt; &lt;input type=&quot;hidden&quot; id=&quot;_form_name&quot; name=&quot;_form_name&quot; value=&quot;addmodify&quot; /&gt; &lt;input type=&quot;hidden&quot; id=&quot;_update&quot; name=&quot;_update&quot; value=&quot;0&quot; /&gt; &lt;input type=&quot;hidden&quot; id=&quot;sec&quot; name=&quot;sec&quot; value=&quot;general&quot; /&gt; &lt;ul class=&quot;nav&quot; id=&quot;nav&quot;&gt;&lt;li id=&quot;nav_general&quot; class=&quot;active&quot;&gt;&lt;a href=&quot;javascript:toggle_section('general')&quot;&gt;General&lt;/a&gt;&lt;/li&gt;&lt;li id=&quot;nav_appearance&quot; &gt;&lt;a href=&quot;javascript:toggle_section('appearance')&quot;&gt;Appearance&lt;/a&gt;&lt;/li&gt;&lt;li id=&quot;nav_state&quot; &gt;&lt;a href=&quot;javascript:toggle_section('state')&quot;&gt;Status&lt;/a&gt;&lt;/li&gt;&lt;li id=&quot;nav_actions&quot; &gt;&lt;a href=&quot;javascript:toggle_section('actions')&quot;&gt;Actions&lt;/a&gt;&lt;/li&gt;&lt;li id=&quot;nav_label&quot; &gt;&lt;a href=&quot;javascript:toggle_section('label')&quot;&gt;Label&lt;/a&gt;&lt;/li&gt;&lt;li id=&quot;nav_worldmap&quot; &gt;&lt;a href=&quot;javascript:toggle_section('worldmap')&quot;&gt;Worldmap&lt;/a&gt;&lt;/li&gt;&lt;/ul&gt;&lt;div id=&quot;sec_general&quot; class=&quot;section&quot; style=&quot;&quot;&gt;&lt;table class=&quot;mytable&quot;&gt;&lt;tr class=&quot;must&quot;&gt;&lt;td class=tdlabel&gt;host_name&lt;/td&gt;&lt;td class=tdbox&gt;&lt;/td&gt;&lt;td class=tdfield&gt;</pre>`

Some outputs:

`[root@localhost var]# journalctl -xr
-- Logs begin at Wed 2019-01-02 13:56:03 EST, end at Thu 2019-01-03 09:44:09 EST. --
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming acknowledgements.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming logentries.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming contactnotificationmethods.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming contactnotifications.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming notifications.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming externalcommands.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming eventhandlers.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming hostchecks.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming servicechecks.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming systemcommands.
Jan 03 09:44:09 localhost.localdomain ndo2db[7217]: Trimming timedevents.
Jan 03 09:43:16 localhost.localdomain sshd[3289]: Connection closed by 127.0.0.1 port 39600 [preauth]
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming acknowledgements.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming logentries.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming contactnotificationmethods.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming contactnotifications.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming notifications.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming externalcommands.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming eventhandlers.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming hostchecks.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming servicechecks.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming systemcommands.
Jan 03 09:43:06 localhost.localdomain ndo2db[7217]: Trimming timedevents.
Jan 03 09:42:05 localhost.localdomain ndo2db[7217]: Trimming acknowledgements.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming logentries.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming contactnotificationmethods.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming contactnotifications.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming notifications.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming externalcommands.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming eventhandlers.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming hostchecks.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming servicechecks.
Jan 03 09:42:04 localhost.localdomain ndo2db[7217]: Trimming systemcommands.`

`[root@localhost var]# tail -25 nagios.log
[1546521678] wproc:   host=linksys-srw224p; service=Uptime; contact=nagiosadmin
[1546521678] wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;
[1546521678] wproc:   stderr line 01: /bin/sh: /bin/mail: No such file or directory
[1546523094] Auto-save of retention data completed successfully.
[1546524001] SERVICE NOTIFICATION: nagiosadmin;linksys-srw224p;Port 1 Link Status;CRITICAL;notify-service-by-email;CRITICAL - Plugin timed out while executing system call
[1546524001] wproc: NOTIFY job 752 from worker Core Worker 7173 is a non-check helper but exited with return code 127
[1546524001] wproc:   host=linksys-srw224p; service=Port 1 Link Status; contact=nagiosadmin
[1546524001] wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;
[1546524001] wproc:   stderr line 01: /bin/sh: /bin/mail: No such file or directory
[1546524543] SERVICE NOTIFICATION: nagiosadmin;linksys-srw224p;Port 1 Bandwidth Usage;UNKNOWN;notify-service-by-email;check_mrtgtraf: Unable to open MRTG log file
[1546524543] wproc: NOTIFY job 757 from worker Core Worker 7174 is a non-check helper but exited with return code 127
[1546524543] wproc:   host=linksys-srw224p; service=Port 1 Bandwidth Usage; contact=nagiosadmin
[1546524543] wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;
[1546524543] wproc:   stderr line 01: /bin/sh: /bin/mail: No such file or directory
[1546525278] SERVICE NOTIFICATION: nagiosadmin;linksys-srw224p;Uptime;CRITICAL;notify-service-by-email;CRITICAL - Plugin timed out while executing system call
[1546525278] wproc: NOTIFY job 767 from worker Core Worker 7172 is a non-check helper but exited with return code 127
[1546525278] wproc:   host=linksys-srw224p; service=Uptime; contact=nagiosadmin
[1546525278] wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;
[1546525278] wproc:   stderr line 01: /bin/sh: /bin/mail: No such file or directory
[1546526694] Auto-save of retention data completed successfully.
[1546527601] SERVICE NOTIFICATION: nagiosadmin;linksys-srw224p;Port 1 Link Status;CRITICAL;notify-service-by-email;CRITICAL - Plugin timed out while executing system call
[1546527601] wproc: NOTIFY job 793 from worker Core Worker 7174 is a non-check helper but exited with return code 127
[1546527601] wproc:   host=linksys-srw224p; service=Port 1 Link Status; contact=nagiosadmin
[1546527601] wproc:   early_timeout=0; exited_ok=1; wait_status=32512; error_code=0;
[1546527601] wproc:   stderr line 01: /bin/sh: /bin/mail: No such file or directory`

Here the versions I install in my linux:

*CentOS Linux release 7.6.1810
*nagvis-1.9.9
*ndoutils-2.1.3
*nagios-4.1.1
*PHP 5.4.16
*MariaDB 5.5.60

Have a great week and thank you !

PD: Sorry for my english.

**Comment by USER1696960** [comment]
update: Check Mariadb and I see tables and data in my Nagios DB.

**Comment by LarsMichelsen** [comment]
Unable to support NDOutils and the related backend. Needs to be done by someone else.

I recommend to use the livestatus backend instead.
