### ISSUE TITLE
Nagvis map is not accessible

### ISSUE THREAD

**Issue by Yuvaraj89888** [NagVis/nagvis#195]
Hi Team,
when i am editing my map suddenly page was not accessible and throwing the following error
Error: (0) in_array() expects parameter 2 to be array, boolean given
URL: /tester/nagvis/frontend/nagvis-js/index.php
File: /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php
Line: 1019
#0 [internal function]: nagvisExceptionErrorHandler(2, 'in_array() expe...', '/opt/omd/versio...', 1019, Array)
#1 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(1019): in_array('worldmap', false)
#2 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(480): GlobalMapCfg->checkMapConfigIsValid()
#3 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(164): GlobalMapCfg->readMapConfig(true)
#4 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(305): NagVisHeaderMenu->getMapList()
#5 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/NagVisHeaderMenu.php(82): NagVisHeaderMenu->getMacros()
#6 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/FrontendModOverview.php(77): NagVisHeaderMenu->__toString()
#7 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/classes/FrontendModOverview.php(55): FrontendModOverview->showViewDialog()
#8 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/server/core/functions/index.php(120): FrontendModOverview->handleAction()
#9 /opt/omd/versions/1.4.0p33.cre/share/nagvis/htdocs/frontend/nagvis-js/index.php(53): require('/opt/omd/versio...')
#10 {main}

please help on this

**Comment by LarsMichelsen** [comment]
The specific map configuration file would be interesting.

Addionally: You are using Checkmk 1.4.0p33 together with an old version of NagVis. This is a bug which might already be fixed in newer versions. I'd recommend to update first.

**Comment by gaius1234** [comment]
How do I update nagvis add-on icinga in centos7?
