### ISSUE TITLE
Map issue after VM migration

### ISSUE THREAD

**Issue by SylvainG69** [NagVis/nagvis#257]
Hi,
I've juste migrata un omd instance from an ubuntu 16.04 to an ubuntu 18..04
I'm running the RAW 1.6.0p11 version with NagVis 1.9.18.
On the old VM php version is 7.0.33-0ubuntu0.16.04.14 and PHP 7.4.6 on the new one.
The map in opening with en error message witch is : 
[code]
Error: (0) Trying to access array offset on value of type int
URL: /ArchiMonitor/nagvis/server/core/ajax_handler.php?mod=Map&act=getMapObjects&show=Anneau&sources=dynmap&header_menu=1&hover_menu=1&context_menu=1&zoom=100&dynmap_init_x=20&dynmap_init_y=700&dynmap_offset_x=30&dynmap_offset_y=30&dynmap_per_row=30&dynmap_sort=a&dynmap_order=asc&_ajaxid=1590579649
File: /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php
Line: 970
#0 /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(970): nagvisExceptionErrorHandler()
#1 /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/classes/GlobalMapCfg.php(489): GlobalMapCfg->verifyObjectIds()
#2 /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/classes/CoreModMap.php(322): GlobalMapCfg->readMapConfig()
#3 /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/classes/CoreModMap.php(105): CoreModMap->getMapObjects()
#4 /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/functions/index.php(120): CoreModMap->handleAction()
#5 /opt/omd/versions/1.6.0p11.cre/share/nagvis/htdocs/server/core/ajax_handler.php(59): require('/opt/omd/versio...')
#6 {main}
[/code]

I think it's a php compatibily issue but I'm not able to solve. Could I get help there?

**Comment by SylvainG69** [comment]
I've just seen the changelog of 1.9.20. It seems solving my problem. I'm going to look for un update solution.

**Comment by SylvainG69** [comment]
I've just seen the changelog of 1.9.20. It seems solving my problem. I'm going to look for un update solution.
