### ISSUE TITLE
Cant manage backends

### ISSUE THREAD

**Issue by MC-brunomendes** [NagVis/nagvis#288]
I've made a clean install of nagvis but when i go to manage backends I get this error:

<html>
<body>
<span style="color: rgb(213, 9, 27); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(254, 186, 187); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Invalid JSON response</span><div class="details" style="margin: 5px 0px 0px; padding: 0px; text-align: left; font-size: 0.8em; color: rgb(213, 9, 27); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Time: 1620830354<br>URL: /nagvis/server/core/ajax_handler.php?mod=MainCfg&amp;act=manageBackends&amp;_ajaxid=1620830354<br>Response:<code style="display: block; overflow: scroll; background-color: rgb(255, 255, 255); color: rgb(0, 0, 0); margin: 2px; padding: 2px;"><h2 style="text-align: left; padding: 3px 10px 2px 2px; line-height: 20px; font-weight: normal; border-bottom: 1px solid rgb(126, 164, 52); color: rgb(67, 179, 207); margin: 5px 0px;">Default Backend</h2><form id="default" name="default" action="javascript:submitForm('/nagvis/server/core/ajax_handler.php?mod=MainCfg&amp;act=manageBackends', 'default');" method="POST">

Default Backend | {"type":"error","message":"Error: (0) Trying to access array offset on value of type nullURL: \/nagvis\/server\/core\/ajax_handler.php?mod=MainCfg&act=manageBackends&_ajaxid=1620830354\nFile: \/usr\/local\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php\nLine: 95\n#0 \/usr\/local\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php(95): nagvisExceptionErrorHandler()\n#1 \/usr\/local\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php(270): ViewManageBackends->defaultForm()\n#2 \/usr\/local\/nagvis\/share\/server\/core\/classes\/CoreModMainCfg.php(52): ViewManageBackends->parse()\n#3 \/usr\/local\/nagvis\/share\/server\/core\/functions\/index.php(120): CoreModMainCfg->handleAction()\n#4 \/usr\/local\/nagvis\/share\/server\/core\/ajax_handler.php(59): require('\/usr\/local\/nagv...')\n#5 {main}<\/code>Output:<h2>Default Backend<\/h2><form id="default" name="default" action="javascript:submitForm('\/nagvis\/server\/core\/ajax_handler.php?mod=MainCfg&amp;act=manageBackends', 'default');" method="POST">\n<input type="hidden" id="_form_name" name="_form_name" value="default" \/>\n<input type="hidden" id="_update" name="_update" value="0" \/>\n<input type="hidden" id="mode" name="mode" value="default" \/>\n<table name="mytable" class="mytable"><tr><td class="tdlabel">Default Backend<\/td><td class="tdfield"><\/pre>","title":"Error: PHP Error"}
-- | --

</form></code></div>
</body>
</html>

**Comment by MC-brunomendes** [comment]
I could really use some help on this.

**Comment by p-collins** [comment]
You need to set a default backend in your config (nagvis.ini.php) for example:

backend="live_1" 

depending what backend id you have set up
