### ISSUE TITLE
Error after new Installation (Ubuntu 22.04)  

### ISSUE THREAD

**Issue by TheUltimateRookieUser** [NagVis/nagvis#340]
Hi there, 
after using nagios for a while I would like to use NagVis. I did an apt get install nagvis on Ubuntu, which runs fine without errors. I could open the nagvis page unter xxx.xxx.xxx.xxx/nagvis and could enter credentials. 

http://xxx.xxx.xxx.xxx/nagvis/frontend/nagvis-js/index.php

shows

 Error: (0) preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated
URL: /nagvis/frontend/nagvis-js/index.php
File: /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php
Line: 1695
#0 [internal function]: nagvisExceptionErrorHandler()
#1 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(1695): preg_match()
#2 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(1302): Dwoo_Compiler->parseFunction()
#3 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Compiler.php(758): Dwoo_Compiler->parse()
#4 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo/Template/String.php(369): Dwoo_Compiler->compile()
#5 /usr/share/nagvis/share/frontend/nagvis-js/ext/dwoo-1.1.0/Dwoo.php(363): Dwoo_Template_String->getCompiledTemplate()
#6 /usr/share/nagvis/share/frontend/nagvis-js/classes/NagVisHeaderMenu.php(85): Dwoo->get()
#7 /usr/share/nagvis/share/frontend/nagvis-js/classes/FrontendModOverview.php(77): NagVisHeaderMenu->__toString()
#8 /usr/share/nagvis/share/frontend/nagvis-js/classes/FrontendModOverview.php(55): FrontendModOverview->showViewDialog()
#9 /usr/share/nagvis/share/server/core/functions/index.php(120): FrontendModOverview->handleAction()
#10 /usr/share/nagvis/share/frontend/nagvis-js/index.php(53): require('...')
#11 {main}

Php is Version 8.1

Ubuntu is 22.04.2 LTS   

Any help is appreciated..

**Comment by jdidierpichatext** [comment]
@TheUltimateRookieUser did you find any solution regarding this issue ?
