### ISSUE TITLE
Error on map load

### ISSUE THREAD

**Issue by guillaumechardin** [NagVis/nagvis#346]
Hello i am facing an issue with one of my server.
When selecting a submap, it crashed with this error : 
```
Error: (0) Undefined array key "ack"
URL: /nagvis/server/core/ajax_handler.php?mod=Map&act=getMapObjects&show=Baie_A&header_menu=1&hover_menu=1&context_menu=1&zoom=100&_ajaxid=1688561307
File: /usr/share/nagvis/share/server/core/classes/objects/NagVisObject.php
Line: 515
#0 /usr/share/nagvis/share/server/core/classes/objects/NagVisObject.php(515): nagvisExceptionErrorHandler()
#1 /usr/share/nagvis/share/server/core/classes/objects/NagVisObject.php(498): NagVisObject::sortStatesByStateValues()
#2 [internal function]: NagVisObject::sortObjectsByState()
#3 /usr/share/nagvis/share/server/core/classes/objects/NagVisObject.php(328): usort()
#4 /usr/share/nagvis/share/server/core/classes/objects/NagVisObject.php(299): NagVisObject->getSortedObjectMembers()
#5 /usr/share/nagvis/share/server/core/classes/objects/NagVisObject.php(386): NagVisObject->getObjectInformation()
#6 /usr/share/nagvis/share/server/core/classes/objects/NagVisStatefulObject.php(434): NagVisObject->parseJson()
#7 /usr/share/nagvis/share/server/core/classes/NagVisMap.php(106): NagVisStatefulObject->parseJson()
#8 /usr/share/nagvis/share/server/core/classes/CoreModMap.php(325): NagVisMap->parseObjectsJson()
#9 /usr/share/nagvis/share/server/core/classes/CoreModMap.php(105): CoreModMap->getMapObjects()
#10 /usr/share/nagvis/share/server/core/functions/index.php(120): CoreModMap->handleAction()
#11 /usr/share/nagvis/share/server/core/ajax_handler.php(59): require('...')
#12 {main}
```

I found out that removing the  "define map { .... } directive in map config file solve this issue. So this is the culprit.

I cas using nagvis 1.9.31 and upgraded to last  1.9.35 to check if it solve this issue : it do not solve.
This system is interfacing nagvis with centreon.

Does anyone know how to solve this bug ?

thanks for your help.

**Comment by guillaumechardin** [comment]
PHP version is 8.0.12.
I found out that this server was updated few days ago maybe issue appear from then, like #345

**Comment by lendropaulo** [comment]
Guillaumechardin, Please could you tell me how you installed this version?

Could you explain to me how to remove the version that comes by default with chckmk?

**Comment by guillaumechardin** [comment]
> Guillaumechardin, Please could you tell me how you installed this version?
I followed the available doc on nagvis website : http://docs.nagvis.org/1.9/en_US/index.html   
  Installation/Upgrade >> manual upgrade

> Could you explain to me how to remove the version that comes by default with chckmk?
I don't know, i do not use chckmk

**Comment by lendropaulo** [comment]
Thank you very much for your feedback. I will try to follow the tutorial to fix the problem.
