### ISSUE TITLE
Centos 7 + Centreon + Nagvis - en Nagvis al entrar en Manage Backends , me da el siguiente error:

### ISSUE THREAD

**Issue by JuanjoMontes** [NagVis/nagvis#365]
Invalid JSON response
Time: 1707429821
URL: /nagvis/server/core/ajax_handler.php?mod=MainCfg&act=manageBackends&_ajaxid=1707429821
Response:

{"type":"error","message":"Error: (0) Trying to access array offset on value of type null
URL: \/nagvis\/server\/core\/ajax_handler.php?mod=MainCfg&act=manageBackends&_ajaxid=1707429873
\nFile: \/usr\/lib\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php
\nLine: 98
\n#0 \/usr\/lib\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php(98): nagvisExceptionErrorHandler()
\n#1 \/usr\/lib\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php(273): ViewManageBackends->defaultForm()
\n#2 \/usr\/lib\/nagvis\/share\/server\/core\/classes\/CoreModMainCfg.php(53): ViewManageBackends->parse()
\n#3 \/usr\/lib\/nagvis\/share\/server\/core\/functions\/index.php(120): CoreModMainCfg->handleAction()
\n#4 \/usr\/lib\/nagvis\/share\/server\/core\/ajax_handler.php(59): require('...')
\n#5 {main}<\/code>Output:
<h2>Default Backend<\/h2><form id="default" name="default" action="javascript:submitForm('\/nagvis\/server\/core\/ajax_handler.php?mod=MainCfg&amp;act=manageBackends', 'default');" method="POST">\n<input type="hidden" id="_form_name" name="_form_name" value="default" \/>\n<input type="hidden" id="_update" name="_update" value="0" \/>\n<input type="hidden" id="mode" name="mode" value="default" \/>\n<table name="mytable" class="mytable"><tr><td class="tdlabel">Default Backend<\/td><td class="tdfield"><\/pre>","title":"Error: PHP Error"}

**Comment by edsonblwolf** [comment]
**_**Clicking on Manager Backends also pops up this error.**_**

`Invalid JSON response<div class="details">
Time: 1734978352<br>
URL: /nagvis/server/core/ajax_handler.php?mod=MainCfg&amp;act=manageBackends&amp;_ajaxid=1734978352<br>
Response: <code><h2>Default Backend</h2><form id="default" name="default" action="javascript:submitForm('/nagvis/server/core/ajax_handler.php?mod=MainCfg&amp;act=manageBackends', 'default');" method="POST">




Default Backend | {"type":"error","message":"Error: (0) Trying to access array offset on nullURL: \/nagvis\/server\/core\/ajax_handler.php?mod=MainCfg&act=manageBackends&_ajaxid=1734978352\nFile: \/usr\/local\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php\nLine: 98\n#0 \/usr\/local\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php(98): nagvisExceptionErrorHandler()\n#1 \/usr\/local\/nagvis\/share\/server\/core\/classes\/ViewManageBackends.php(273): ViewManageBackends->defaultForm()\n#2 \/usr\/local\/nagvis\/share\/server\/core\/classes\/CoreModMainCfg.php(53): ViewManageBackends->parse()\n#3 \/usr\/local\/nagvis\/share\/server\/core\/functions\/index.php(120): CoreModMainCfg->handleAction()\n#4 \/usr\/local\/nagvis\/share\/server\/core\/ajax_handler.php(59): require('...')\n#5 {main}<\/code>Output: <h2>Default Backend<\/h2><form id="default" name="default" action="javascript:submitForm('\/nagvis\/server\/core\/ajax_handler.php?mod=MainCfg&amp;act=manageBackends', 'default');" method="POST">\n<input type="hidden" id="_form_name" name="_form_name" value="default" \/>\n<input type="hidden" id="_update" name="_update" value="0" \/>\n<input type="hidden" id="mode" name="mode" value="default" \/>\n<table name="mytable" class="mytable"><tr><td class="tdlabel">Default Backend<\/td><td class="tdfield"><\/pre>","title":"Error: PHP Error"}
-- | --


</form></code></div>`
