### ISSUE TITLE
Nagvis no work with omd 5.40

### ISSUE THREAD

**Issue by fbaschin** [NagVis/nagvis#386]
I have Update from omd (console labs) 5.30 to 5.40 
Nagvis 1.9.44 did not work

Error: (0) require_once(gettext.inc): Failed to open stream: No such file or directory
URL: /nagios/nagvis/frontend/nagvis-js/index.php
File: /opt/omd/sites/nagios/local/share/nagvis/htdocs/server/core/classes/GlobalLanguage.php
Line: 48
#0 /opt/omd/sites/nagios/local/share/nagvis/htdocs/server/core/classes/GlobalLanguage.php(48): nagvisExceptionErrorHandler()
#1 /opt/omd/sites/nagios/local/share/nagvis/htdocs/server/core/classes/GlobalLanguage.php(48): require_once()
#2 /opt/omd/sites/nagios/local/share/nagvis/htdocs/server/core/functions/core.php(55): GlobalLanguage->__construct()
#3 /opt/omd/sites/nagios/local/share/nagvis/htdocs/frontend/nagvis-js/index.php(42): require('...')
#4 {main}

After switch back to omd 5.30 it works
System is Debian 12 with latest patches

**Comment by fbaschin** [comment]
[Solution]
cd /omd/sites/nagios/share
ln -s /opt/omd/sites/nagios/local/share/nagvis/ nagvis
